version: 2

workflows:
  version: 2
  testing:
    jobs:
      - save
      - wait:
          requires: [save]
      - load:
          requires: [wait]

jobs:
  save:
    docker:
      - image: circleci/golang
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker pull circleci/openjdk
  wait:
    docker:
      - image: circleci/golang
    steps:
      - run: |
          # Give vm-service some time to detach and unmount the volume
          sleep 60
  load:
    docker:
      - image: circleci/golang
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          # We expect to see the image we pulled in the save job
          docker image ls
